/**
 * Registry renderer (draft/EMULATOR.md §2, ADAPTING-AN-AGENT step 4):
 * registry.ts is GENERATED from surface/model/claude@2.1.207 — the model is
 * canonical, this is the projection. Consumed by surface/generate-registry.mjs
 * (CLI write) and src/registry.test.ts (byte-parity freshness check).
 *
 * Self-contained by design (no runtime imports — the model is passed in):
 * node type stripping executes this file from the .mjs CLI, and node does not
 * remap `.js`-suffixed relative imports.
 *
 * Output is prettier-stable: every registry entry stays multiline (prettier
 * preserves objects whose `{` is followed by a newline), so regeneration is
 * byte-stable across `pnpm format` runs.
 */

import type { SurfaceModel } from '@vibecook/chopsticks-emulator';

/** Single-quoted JS string literal (prettier style). */
function jsStr(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function renderRegistry(model: SurfaceModel): string {
  /** Prettier wraps a property whose line exceeds 120 columns as `key:` + indented value. */
  const prop = (key: string, value: string): string => {
    const inline = `    ${key}: ${value},`;
    return inline.length <= 120 ? inline : `    ${key}:\n      ${value},`;
  };
  const entries = model.events
    .map((event) => {
      const lines = [
        prop('event', jsStr(event.event)),
        prop('transport', jsStr(event.transport ?? '')),
        prop('confidence', jsStr(event.confidence)),
        prop('timeoutSec', String(event.timeoutSec)),
      ];
      if (event.notes) lines.push(prop('notes', jsStr(event.notes)));
      return `  {\n${lines.join('\n')}\n  },`;
    })
    .join('\n');

  return `/**
 * GENERATED by surface/generate-registry.mjs from surface/model/claude@2.1.207
 * — do not hand-edit. Edit the model and regenerate; src/registry.test.ts
 * enforces byte-parity.
 *
 * Claude Code hook-event registry — DATA, not code (DESIGN §16.5: settings
 * are generated from a registry, never handwritten; §10: capability-probe,
 * don't assume).
 *
 * Ground truth: the Phase 0 headless census and the M1 interactive census
 * (draft/HOOK-SURFACE-FINDINGS.md), captured against Claude Code 2.1.207 and
 * distilled into surface/model/claude@2.1.207 (draft/EMULATOR.md §2). Every
 * 'verified-*' event has a representative payload fixture in
 * @vibecook/chopsticks-testing (fixtures/hooks/<Event>.jsonl).
 *
 * Transport preference implements the hybrid bridge (DESIGN §16.4):
 * high-frequency events go over HTTP (no forwarder process per event);
 * low-frequency lifecycle events tolerate the command forwarder, which is
 * also the fallback if a probe finds an event type without HTTP support.
 */

export type HookTransport = 'http' | 'command';

export type HookConfidence =
  | 'verified-headless' // fired in \`-p\` runs A–F
  | 'verified-interactive' // fired only under the M1 PTY census
  | 'unverified'; // name known (spaghetti HookEventName union); never observed

export interface HookEventSpec {
  /** Claude Code \`hook_event_name\`. */
  event: string;
  transport: HookTransport;
  confidence: HookConfidence;
  /** Hook timeout written into generated settings. */
  timeoutSec: number;
  /** Payload fields beyond the common envelope that the normalizer relies on. */
  notes?: string;
}

export const CLAUDE_HOOK_REGISTRY: readonly HookEventSpec[] = [
${entries}
];

export function getHookSpec(event: string): HookEventSpec | undefined {
  return CLAUDE_HOOK_REGISTRY.find((s) => s.event === event);
}

/** Events safe to wire by default: observed at least once on a real session. */
export function verifiedHookEvents(): HookEventSpec[] {
  return CLAUDE_HOOK_REGISTRY.filter((s) => s.confidence !== 'unverified');
}
`;
}
